// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: message.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SendMsg_SendMsg_FullMethodName = "/SendMsg/SendMsg"
)

// SendMsgClient is the client API for SendMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMsgClient interface {
	SendMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sendMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMsgClient(cc grpc.ClientConnInterface) SendMsgClient {
	return &sendMsgClient{cc}
}

func (c *sendMsgClient) SendMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, SendMsg_SendMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMsgServer is the server API for SendMsg service.
// All implementations must embed UnimplementedSendMsgServer
// for forward compatibility
type SendMsgServer interface {
	SendMsg(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSendMsgServer()
}

// UnimplementedSendMsgServer must be embedded to have forward compatible implementations.
type UnimplementedSendMsgServer struct {
}

func (UnimplementedSendMsgServer) SendMsg(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedSendMsgServer) mustEmbedUnimplementedSendMsgServer() {}

// UnsafeSendMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMsgServer will
// result in compilation errors.
type UnsafeSendMsgServer interface {
	mustEmbedUnimplementedSendMsgServer()
}

func RegisterSendMsgServer(s grpc.ServiceRegistrar, srv SendMsgServer) {
	s.RegisterService(&SendMsg_ServiceDesc, srv)
}

func _SendMsg_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMsgServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendMsg_SendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMsgServer).SendMsg(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMsg_ServiceDesc is the grpc.ServiceDesc for SendMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SendMsg",
	HandlerType: (*SendMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _SendMsg_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
